apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-demo
spec:
  replicas: 3  # or 3 for mirrored and quorum queues
  service:
    type: LoadBalancer
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream_management # Enable Streaming
  #   additionalConfig: |
  #     default_user=guest
  #     default_pass=guest  
  # persistence:
  #   storage: "2Gi"
