apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rmq-demo
spec:
  replicas: 1  # or 3 for mirrored and quorum queues
  service:
    type: LoadBalancer
  # rabbitmq:  
  #   additionalConfig: |
  #     default_user=guest
  #     default_pass=guest  
  # persistence:
  #   storage: "2Gi"
